# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title-bold: Yanghe Feng
email: fengyanghe@gmail.com
description: Yanghe Feng, Ph.D, Research Assistant Professor with Information System and Engineering Lab in National University of Defense Technology, Changsha, 410073, P.R.China
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fengyanghe.github.io" # the base hostname & protocol for your site
author: 
street_address: National University of Defense Tecnology
city: Changsha
state: Hunan
zip_code: 410073
country: China
phone: 07318457661

# Plugins
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages" 
tiles-count: 8
highlighter: pygments
excerpt_separator: <!--excerpt-->

# Social settings
500px_url: 
facebook_url: 
github_url: https://www.github.com/fengyanghe
gitlab_url: 
googleplus_url: 
instagram_url:
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: 

# Build settings
markdown: kramdown

# Plugin: jekyll-seo-tag
twitter:
  username: 
# Add one or more of the following
facebook:
  app_id: 
  publisher: 
  admins: 
logo:
google_site_verification: 
